grant_csv_titles = [
    "Data Source",
    "Publisher:Name",
    "Identifier",
    "Title",
    "Description",
    "Currency",
    "Amount Awarded",
    "Award Date",
    "URL",
    "Planned Dates:Duration (months)",
    "Recipient Org:Identifier",
    "Recipient Org:Name",
    "Recipient Org:Charity Number",
    "Recipient Org:Company Number",
    "Recipient Org:Location:0:Geographic Code Type",
    "Recipient Org:Location:0:Geographic Code",
    "Recipient Org:Location:0:Name",
    "Recipient Org:Location:1:Geographic Code Type",
    "Recipient Org:Location:1:Geographic Code",
    "Recipient Org:Location:1:Name",
    "Recipient Org:Location:2:Geographic Code Type",
    "Recipient Org:Location:2:Geographic Code",
    "Recipient Org:Location:2:Name",
    "Recipient Region",
    "Recipient District",
    "Recipient Ward",
    "Beneficiary Location:Name",
    "Beneficiary Location:Country Code",
    "Beneficiary Location:Geographic Code",
    "Beneficiary Location:Geographic Code Type",
    "Funding Org:Identifier",
    "Funding Org:Name",
    "Retrieved for use in GrantNav",
    "License (see note)",
    "Note: this file also contains OS data © Crown copyright and database right 2016, Royal Mail data © Royal Mail copyright and Database right 2016, National Statistics data © Crown copyright and database right 2016, see http://grantnav.org/datasets/ for more information.",
]

grant_csv_paths = [
    "dataset.distribution.0.downloadURL",
    "dataset.publisher.name",
    "result.id",
    "result.title",
    "result.description",
    "result.currency",
    "result.amountAwarded",
    "result.awardDate",
    "result.recipientOrganization.0.url",
    "result.plannedDate.duration",
    "result.recipientOrganization.0.id",
    "result.recipientOrganization.0.name",
    "result.recipientOrganization.0.charityNumber",
    "result.recipientOrganization.0.companyNumber",
    "result.recipientOrganization.0.location.0.geoCodeType",
    "result.recipientOrganization.0.location.0.geoCode",
    "result.recipientOrganization.0.location.0.name",
    "result.recipientOrganization.0.location.1.geoCodeType",
    "result.recipientOrganization.0.location.1.geoCode",
    "result.recipientOrganization.0.location.1.name",
    "result.recipientOrganization.0.location.2.geoCodeType",
    "result.recipientOrganization.0.location.2.geoCode",
    "result.recipientOrganization.0.location.2.name",
    "result.recipientRegionName",
    "result.recipientDistrictName",
    "result.recipientWardName",
    "result.beneficiaryLocation.name",
    "result.beneficiaryLocation.countryCode",
    "result.beneficiaryLocation.geoCode",
    "result.beneficiaryLocation.geoCodeType",
    "result.fundingOrganization.0.id",
    "result.fundingOrganization.0.name",
    "dataset.datagetter_metadata.datetime_downloaded",
    "dataset.license"
]

org_csv_titles = [
    "Grants",
    "Total",
    "Average",
    "Largest",
    "Smallest"
]

recipient_csv_titles = ["Recipient Name", "Recipient ID"] + org_csv_titles
funder_csv_titles = ["Funder Name", "Funder ID"] + org_csv_titles

org_csv_paths = [
    "org_name",
    "org_id",
    "count",
    "sum",
    "avg",
    "max",
    "min"
]
