name: Lint
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        architecture: 'x64'
        cache: 'pip'

    - run: pip install -r requirements.txt
    - run: pip install -r requirements_dev.txt

    - run: flake8 .
    - run: npm install
    - run: ./node_modules/eslint/bin/eslint.js --ext .js --ext .html grantnav/frontend/templates/**
